version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  nginx:
    container_name: nginx1
    restart: always
    image: nginx:stable-perl
    volumes:
      - static_files:/code/static
      - ./nginx/user_conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - web
      - db
  pgadmin:
    container_name: pgadmin4_container1
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres_data:
  static_files:
  pgadmin:
