from faker import Faker
from faker.providers import DynamicProvider

class CustomProvider:

    def school_subjects_provider():

        school_subjects_provider = DynamicProvider(
            provider_name="school_subject",
            elements=[
                    "Mathematics",
                    "Science",
                    "English",
                    "History",
                    "Geography",
                    "Physical Education",
                    "Art",
                    "Music",
                    "Computer Science",
                    "Biology",
                    "Chemistry",
                    "Physics",
                    "Social Studies",
                    "Spanish",
                    "French",
                    "German",
                    "Chinese",
                    "Japanese",
                    "Literature",
                    "Economics",
                    "Psychology",
                    "Sociology",
                    "Political Science",
                    "Physical Education",
                    "Health Education",
                    "Environmental Science",
                    "Engineering",
                    "Philosophy",
                    "Religious Studies",
                    "Drama",
                    "Home Economics",
                    "Astronomy",
                    "Civics",
                    "Anthropology",
                    "Business Studies",
                    "Statistics",
                    "Law",
                    "Media Studies",
                    "Design and Technology",
                    "Agriculture",
                    "Gymnastics",
                    "Foreign Languages",
                    "Ethics",
                    "Information Technology",
                    "Marine Biology",
                    "Archaeology",
                    "Criminal Justice",
                ],
        )

        return school_subjects_provider

    def school_courses_provider():

        school_courses_provider = DynamicProvider(
            provider_name="school_course",
            elements= [
                    "Mathematics",
                    "English Literature",
                    "Biology",
                    "Chemistry",
                    "Physics",
                    "History",
                    "Geography",
                    "Physical Education",
                    "Art",
                    "Music",
                    "Computer Science",
                    "Spanish",
                    "French",
                    "German",
                    "Latin",
                    "Economics",
                    "Psychology",
                    "Sociology",
                    "Political Science",
                    "Environmental Science",
                    "Astronomy",
                    "Philosophy",
                    "Religious Studies",
                    "Statistics",
                    "Calculus",
                    "Algebra",
                    "Geometry",
                    "Civics",
                    "Health Education",
                    "Business Management",
                    "Marketing",
                    "Accounting",
                    "Finance",
                    "Literary Analysis",
                    "Creative Writing",
                    "Drama",
                    "Physical Education",
                    "Home Economics",
                    "Culinary Arts",
                    "Auto Mechanics",
                    "Woodworking",
                    "Graphic Design",
                    "Web Development",
                    "Robotics",
                    "Film Studies",
                    "Photography",
                    "World History",
                    "U.S. History",
                    "European History",
                    "Asian History",
                    "African History",
                    "Middle Eastern History",
                    "Global Studies",
                    "Criminal Justice",
                    "Forensic Science",
                    "Meteorology",
                    "Anthropology",
                    "Sustainability",
                    "Environmental Ethics",
                    "Human Anatomy",
                    "Botany",
                    "Zoology",
                    "Microbiology",
                    "Genetics",
                    "Neuroscience",
                    "Public Speaking",
                    "Debate",
                    "Ethics",
                    "Human Rights",
                    "Gender Studies",
                    "Linguistics",
                    "Critical Thinking",
                    "Digital Marketing",
                    "Data Science",
                    "Machine Learning",
                    "Ethical Hacking",
                    "Mobile App Development",
                    "Game Design",
                    "Animation",
                    "Music Theory",
                    "Music Production",
                    "Sculpture",
                    "Ceramics",
                    "Fashion Design",
                    "Theater Production",
                    "Carpentry",
                    "Welding",
                    "Electrical Engineering",
                    "Chemical Engineering",
                    "Civil Engineering",
                    "Environmental Engineering",
                    "Architecture",
                    "Urban Planning",
                    "Epidemiology",
                    "Nutrition",
                    "Physical Therapy",
                    "Nursing",
                    "Veterinary Science",
                    "Dentistry",
                    "Pharmacy",
                    "Law",
                    "International Relations",
                    "Comparative Literature",
                    "Classical Studies",
                    "Creative Writing",
                    "Ethnomusicology",
                    "Art History",
                    "Molecular Biology",
                    "Astrophysics",
                    "Religion and Science",
                    "Human Geography",
                    "Criminology",
                    "Mental Health Counseling",
                    "Early Childhood Education",
                    "Special Education",
                    "Library Science",
                    "Film Production",
                    "Game Development",
                    "Virtual Reality Design",
            ]
        )

        return school_courses_provider