from faker import Faker
from faker.providers import DynamicProvider

school_subjects_provider = DynamicProvider(
     provider_name="school_subject",
     elements=[
            "Mathematics",
            "Science",
            "English",
            "History",
            "Geography",
            "Physical Education",
            "Art",
            "Music",
            "Computer Science",
            "Biology",
            "Chemistry",
            "Physics",
            "Social Studies",
            "Spanish",
            "French",
            "German",
            "Chinese",
            "Japanese",
            "Literature",
            "Economics",
            "Psychology",
            "Sociology",
            "Political Science",
            "Physical Education",
            "Health Education",
            "Environmental Science",
            "Engineering",
            "Philosophy",
            "Religious Studies",
            "Drama",
            "Home Economics",
            "Astronomy",
            "Civics",
            "Anthropology",
            "Business Studies",
            "Statistics",
            "Law",
            "Media Studies",
            "Design and Technology",
            "Agriculture",
            "Gymnastics",
            "Foreign Languages",
            "Ethics",
            "Information Technology",
            "Marine Biology",
            "Archaeology",
            "Criminal Justice",
        ],
)

Faker.add_provider('school_subject')