# Generated by Django 4.2.4 on 2023-09-28 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='person',
        ),
        migrations.AddField(
            model_name='school',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='instructors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
