# Generated by Django 4.2.4 on 2023-09-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_school_person_school_instructors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='country',
        ),
    ]
