# Generated by Django 4.2.4 on 2023-10-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_remove_school_address_remove_school_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
